In [1]:
!pip install --upgrade --no-cache-dir gdown > /dev/null
!gdown --id 1PFFxswC-YFz5UwWytak1JA40Ri2Ewy67

/usr/local/lib/python3.7/dist-packages/gdown/cli.py:131: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  category=FutureWarning,
Downloading...
From: https://drive.google.com/uc?id=1PFFxswC-YFz5UwWytak1JA40Ri2Ewy67
To: /content/winequality-red.csv
100% 101k/101k [00:00<00:00, 71.3MB/s]

In [2]:
import pandas as pd

df = pd.read_csv("winequality-red.csv")
df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:

df.reset_index(inplace=True)
df.head()

,index,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [4]:
df['index'] = df['index']+1

In [5]:
def col_name(df):
    col_list =[]
    for name in df.columns:
        col_list.append(name.replace(' ',''))
    df.columns = col_list
    return df

def round_col(df):
    for i in df:
        # print(i)
        if(type(i) is not int):
            return round(i,2)

In [6]:
for i in df:
    df.apply(round_col)

In [7]:
df

,index,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,1,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,2,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,3,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,4,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,5,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1594,1595,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,1596,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,1597,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,1598,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,1599,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [8]:
df = col_name(df)

In [9]:
col = list(df.columns)
col.remove('index')

In [10]:
import sqlite3


conn = sqlite3.connect("winequality-red.db")
cur = conn.cursor()

cur.execute(f"""
    CREATE TABLE quality_data(
    idx INTEGER PRIMARY KEY,
    {col[0]} FLAOT,
    {col[1]} FLAOT,
    {col[2]} FLAOT,
    {col[3]} FLAOT,
    {col[4]} FLAOT,
    {col[5]} FLAOT,
    {col[6]} FLAOT,
    {col[7]} FLAOT,
    {col[8]} FLAOT,
    {col[9]} FLAOT,
    {col[10]} FLAOT,
    {col[11]} INTEGER);""")
conn.commit()

In [11]:
tuple_data = [tuple(x) for x in df.to_records(index=False)]
for i in tuple_data:
    temp = (int(i[0]),float(i[1]),float(i[2]),float(i[3]),float(i[4]),float(i[5]),float(i[6]),float(i[7]),float(i[8]),float(i[9]),float(i[10]),float(i[11]),int(i[12]))
    cur.execute(f"INSERT INTO quality_data VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?);",temp)